### ISSUE TITLE
Some questions about KVM_NITRO functions!

### ISSUE THREAD

**Issue by bigbigbanana** [KVM-VMI/nitro#30]
Hello,recently i am doing reseraching on the nitro project and i am confused about some KVM_NITRO functions,could you tell me what's meaning of these functions?
![2017-08-28 10_39_08](https://user-images.githubusercontent.com/24928429/29761605-9b052028-8bfc-11e7-838c-83b94043f371.png)

**Comment by Wenzel** [comment]
Hi,

please take a look at this wiki page that i wrote a few months ago : https://github.com/Wenzel/kvm-vmi/wiki

Briefly:
- ATTACH_VM will get the vm file descriptor
- ATTACH_VCPU will get the vcpu file descriptors
- then the traps are set
- you use the vcpu file descriptor to send the GET_EVENT ioctl, and CONTINUE_VM once you are done processing it.

Regards.
