### ISSUE TITLE
Minor mistake in libvmi.py

### ISSUE THREAD

**Issue by aghamir** [KVM-VMI/nitro#47]
At this line https://github.com/KVM-VMI/nitro/blob/master/nitro/libvmi.py#L124, `vmi_read_va` must be changed to `vmi_write_va`

**Comment by Wenzel** [comment]
Crap.
You are right :D

I'll fix it right away.
Meanwhile, i have worked on a new CFFI wrapper which supports most of libvmi API and created a PR so that it becomes the new official python binding.
https://github.com/libvmi/libvmi/pull/532

Thanks !
