### ISSUE TITLE
problem about the nitro/readme.md

### ISSUE THREAD

**Issue by Lixiaomingg** [KVM-VMI/nitro#54]
you say " (Nitro only supports for now Windows XP x64 and Windows 7 x64, see the Note section below)" and " Start Nitro as root (go to the Notes section to see how to start it as a normal user)" ,
but i can't find the "Notes" section.
Could you tell me how to start the nitro as root ?
when i firstly use nitro , i input the "# ./main.py --nobackend nitro_win7x64", i get the result below:

kvm.py", line 140, in attach_vm
    raise RuntimeError('Error: fail to attach to the VM ')
RuntimeError: Error: fail to attach to the VM 

how can i solve the problem ?

**Comment by Wenzel** [comment]
Hi !

it seems i removed the `Notes` section in a previous README update, sorry !

Nitro doesn't need root access anymore.

Did you installed the modified kernel ?
What's the output of `uname -a` ?

**Comment by Lixiaomingg** [comment]
Thank you very much ! 
After i install the new kernel,all problems are solved.
At the beginning ,i did not note that need to installed the modified kernel.However,thank you very much
