### ISSUE TITLE
A question about  get syscall argument value.

### ISSUE THREAD

**Issue by bigbigbanana** [KVM-VMI/nitro#64]
Hello,i print all of sys_access and sys_call registers,but i found the return value of sys_access or sys_mmap saved in rax is not the same as strace.Why？
![0427_1](https://user-images.githubusercontent.com/24928429/39391204-83f9f4f4-4ad2-11e8-9c65-b7af2ea0edf6.jpg)

**Comment by bigbigbanana** [comment]
Is there anybody can help me?

**Comment by Wenzel** [comment]
Hi,

right now, i don't know,
- check if these are the exact same syscalls between nitro and strace (maybe strace generate more syscalls)
- investigate by yourself.

**Comment by bigbigbanana** [comment]
Hello,according to my current knowledge,nitro can only get system call,can nitro be used in other fields like malware analysis,i mean only in linux not include windows,could you give me some ideas?
