### ISSUE TITLE
Invalid Qemu command line argument definitions in domain template

### ISSUE THREAD

**Issue by Soft** [KVM-VMI/nitro#65]
Are you sure these are correct? At least my Qemu instance complained about unknown command line flags. I think the correct from is to split the `-object`, `-chardev`, and `-accel` flags into their own `qemu:arg` instances. 

https://github.com/KVM-VMI/nitro/blob/c71e5853fbf4038f34a08278033c66e0c5c137cb/tests/vm_templates/template_domain.xml#L6-L9

**Comment by Wenzel** [comment]
hi !
yes, you are right, and i should have pushed my fixed version of the template_domain.xml
my bad.

**Comment by Wenzel** [comment]
it's already there.
https://github.com/KVM-VMI/nitro/blob/kvmi/tests/vm_templates/template_domain.xml

which branch are you looking at ?
everything is on the `kvmi` branch

**Comment by Soft** [comment]
Oh I was looking at the one referenced by the kvmi branch on the kvm-vmi repo

**Comment by Wenzel** [comment]
maybe we need to update the submodules.
don't forget that they track specific commits, not branches ;)

**Comment by Wenzel** [comment]
Done.
sorry for the confusion

**Comment by Soft** [comment]
Thanks, I just assumed the referenced commit was like a known good state or something
